# Generated by Django 2.2.28 on 2023-11-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etabotapp', '0009_auto_20221024_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth1token',
            name='oauth_token',
            field=models.CharField(max_length=65536),
        ),
        migrations.AlterField(
            model_name='oauth1token',
            name='oauth_token_secret',
            field=models.CharField(max_length=65536),
        ),
        migrations.AlterField(
            model_name='oauth2coderequest',
            name='state',
            field=models.CharField(max_length=65536),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='access_token',
            field=models.CharField(max_length=65536),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='refresh_token',
            field=models.CharField(max_length=65536, null=True),
        ),
    ]
